development:
  adapter: postgresql
  encoding: unicode
  database: funnel_development
  pool: 5
  username: brandon

  password:

test:
  adapter: postgresql
  encoding: unicode
  database: funnel_test
  pool: 5
  username: brandon

  password:
  min_messages: WARNING
